server:
  port: ${PORT:8081}

spring:
  application:
    name: demo-spring-boot

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/d22_xdweb_users?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
